export type Framework = Record<"value" | "label", string>;
export const LANGUAGES: Framework[] = [
  { value: "en", label: "🇬🇧 🇺🇸 English" },
  { value: "zh", label: "🇨🇳 中文" },
  { value: "es", label: "🇪🇸 Español" },
  { value: "ar", label: "🇸🇦 العربية" },
  { value: "hi", label: "🇮🇳 हिन्दी" },
  { value: "bn", label: "🇧🇩 বাংলা" },
  { value: "pt", label: "🇵🇹 Português" },
  { value: "ru", label: "🇷🇺 Русский" },
  { value: "ja", label: "🇯🇵 日本語" },
  { value: "pa", label: "🇮🇳 ਪੰਜਾਬੀ" },
  { value: "de", label: "🇩🇪 Deutsch" },
  { value: "ms", label: "🇲🇾 Bahasa Melayu" },
  { value: "id", label: "🇮🇩 Bahasa Indonesia" },
  { value: "fr", label: "🇫🇷 Français" },
  { value: "ur", label: "🇵🇰 اردو" },
  { value: "ta", label: "🇮🇳 தமிழ்" },
  { value: "fa", label: "🇮🇷 فارسی" },
  { value: "tr", label: "🇹🇷 Türkçe" },
  { value: "ko", label: "🇰🇷 한국어" },
  { value: "it", label: "🇮🇹 Italiano" },
  { value: "vi", label: "🇻🇳 Tiếng Việt" },
];
